// Kulsums Collection: builds search-engine pages from the live catalogue.
// Run by GitHub Actions (.github/workflows/seo.yml), or by hand: node scripts/build-seo.mjs
//
// For every live product it writes products/<name>.html, so https://yoursite/products/<name> is a real page
// with its own title, description, photo, price and Google product data, readable without JavaScript.
// Also: collections/<name>.html, pages/*.html, offers.html and the other shop pages, 404.html, sitemap.xml, robots.txt.
// Each page is index.html with the right details filled in, so the full store still opens on top of it.
// Uses only the public data the store already shows to shoppers (the same public key as config.js).
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, unlinkSync } from "node:fs";
import { join } from "node:path";

const MARK = "<!-- generated by scripts/build-seo.mjs -->";
const root = process.cwd();
const read = (f) => readFileSync(join(root, f), "utf8");

// ---------- settings ----------
const cfg = read("config.js");
const SB_URL = (cfg.match(/supabaseUrl\s*:\s*['"]([^'"]+)['"]/) || [])[1];
const SB_KEY = (cfg.match(/supabaseKey\s*:\s*['"]([^'"]+)['"]/) || [])[1];
if (!SB_URL || !SB_KEY) { console.error("config.js does not have supabaseUrl and supabaseKey."); process.exit(1); }

async function kv(keys) {
  const url = `${SB_URL.replace(/\/$/, "")}/rest/v1/kv?select=key,value&key=in.(${keys.map((k) => `"${k}"`).join(",")})`;
  const r = await fetch(url, { headers: { apikey: SB_KEY, Authorization: `Bearer ${SB_KEY}` } });
  if (!r.ok) throw new Error(`Supabase said ${r.status}: ${await r.text()}`);
  return Object.fromEntries((await r.json()).map((x) => [x.key, x.value]));
}
const data = await kv(["kc:settings", "kc:categories", "kc:catalog"]);
const st = data["kc:settings"] || {};
const cats = data["kc:categories"] || [];
const catalog = data["kc:catalog"] || [];
const brand = st.brand || "Kulsums Collection";
const cname = existsSync(join(root, "CNAME")) ? read("CNAME").trim() : "";
let SITE = String(process.env.SITE_URL || st.seo?.siteUrl || (cname ? `https://${cname}` : "")).trim().replace(/[#?].*$/, "").replace(/\/?$/, "/");
if (!/^https?:\/\//.test(SITE)) { console.error("Set your website address: add a CNAME file, or Settings > Search and sharing > Website address, or SITE_URL."); process.exit(1); }
const ROOT = new URL(SITE).pathname; // "/" for kulsumscollection.com
const abs = (p) => SITE + p.replace(/^\//, "");

// ---------- the same address rules as the store ----------
const slugify = (t) => String(t || "").toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/&/g, " and ").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 70) || "item";
const prodSlug = (p) => p.slug || `${slugify(p.title)}-${String(p.code || p.id).toLowerCase()}`;
const catSlug = (c) => c.slug || (/^[a-z0-9-]{2,40}$/.test(c.id) ? c.id : slugify(c.name));
const esc = (s) => String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
const cut = (s, n) => { s = String(s || "").replace(/\s+/g, " ").trim(); return s.length > n ? s.slice(0, n - 1).replace(/\s\S*$/, "") + "…" : s; };
const money = (n) => (n == null || n === "" ? "" : "₹" + Number(n).toLocaleString("en-IN"));
const imgOf = (p) => { const u = p.media?.imgs?.[0] || p.media?.th || ""; return /^https?:\/\//.test(u) ? u : ""; };

const catById = Object.fromEntries(cats.map((c) => [c.id, c]));
const catOn = (c) => { for (let x = c, i = 0; x && i < 5; x = catById[x.parent], i++) if (x.enabled === false) return false; return !!c; };
const products = catalog.filter((p) => p.published !== false && catOn(catById[p.category] || { enabled: true })).sort((a, b) => (b.createdAt || 0) - (a.createdAt || 0));
const used = new Set();
for (const p of products) { let s = prodSlug(p), b = s, i = 2; while (used.has(s)) s = `${b}-${i++}`; used.add(s); p._slug = s; }
const groupIds = (c) => [c.id, ...cats.filter((x) => x.parent === c.id).map((x) => x.id)];
const mainCats = cats.filter((c) => c.id !== "others" && catOn(c) && !c.parent && products.some((p) => groupIds(c).includes(p.category)));   // only collections that have products
const newDays = st.catalog?.newDays || 14;
const fresh = products.filter((p) => Date.now() - (p.createdAt || 0) < newDays * 864e5);
const newList = [...fresh, ...products.filter((p) => !fresh.includes(p))].slice(0, 10);

// ---------- page template ----------
const template = read("index.html");
function fixPaths(html) {
  // Pages live in sub-folders, so file names outside the scripts become absolute (/config.js, /kulsums-logo.png).
  return html.split(/(<script\b[^>]*>[\s\S]*?<\/script>)/i).map((part, i) => (i % 2 ? part.replace(/(<script\b[^>]*\bsrc=")(?!https?:|\/|data:)([^"]+)"/i, `$1${ROOT}$2"`)
    : part.replace(/\b(src|href|content)="(?!https?:|data:|#|\/|mailto:|tel:|\$|width=|index,|summary|website|en_IN|#)([\w./-]+\.(?:js|png|jpe?g|webp|svg|ico|txt|json|xml|html))"/g, `$1="${ROOT}$2"`))).join("");
}
function page({ title, desc, url, image, type = "website", noindex = false, ld = [], body = "" }) {
  let h = fixPaths(template);
  const set = (re, val) => { h = re.test(h) ? h.replace(re, val) : h.replace("</head>", val + "\n</head>"); };
  set(/<title>[\s\S]*?<\/title>/, `<title>${esc(title)}</title>`);
  set(/<meta name="description"[^>]*>/, `<meta name="description" content="${esc(desc)}">`);
  set(/<meta name="robots"[^>]*>/, `<meta name="robots" content="${noindex ? "noindex,follow" : "index,follow,max-image-preview:large"}">`);
  set(/<meta property="og:title"[^>]*>/, `<meta property="og:title" content="${esc(title)}">`);
  set(/<meta property="og:description"[^>]*>/, `<meta property="og:description" content="${esc(desc)}">`);
  set(/<meta property="og:type"[^>]*>/, `<meta property="og:type" content="${type}">`);
  if (image) set(/<meta property="og:image"[^>]*>/, `<meta property="og:image" content="${esc(image)}">`);
  const extra = [`<link rel="canonical" href="${esc(url)}">`, `<meta property="og:url" content="${esc(url)}">`, `<meta name="twitter:title" content="${esc(title)}">`, `<meta name="twitter:description" content="${esc(desc)}">`,
    image ? `<meta name="twitter:image" content="${esc(image)}">` : "", ld.length ? `<script type="application/ld+json">${JSON.stringify(ld.length === 1 ? ld[0] : { "@context": "https://schema.org", "@graph": ld }).replace(/</g, "\\u003c")}</script>` : ""].filter(Boolean).join("\n");
  h = h.replace("</head>", `${MARK}\n${extra}\n</head>`);
  if (body) h = h.replace(/<div id="app">[\s\S]*?<\/div><\/div>/, `<div id="app"><main class="shop-main ssr" id="main" style="max-width:1100px;margin:0 auto;padding:24px 20px;font-family:system-ui,sans-serif">${body}</main></div>`);
  return h;
}
const nav = () => `<nav aria-label="Shop"><a href="${ROOT}">Home</a> · <a href="${ROOT}collections/new-arrivals">New arrivals</a>${mainCats.map((c) => ` · <a href="${ROOT}collections/${catSlug(c)}">${esc(c.name)}</a>`).join("")} · <a href="${ROOT}pages/about-us">About us</a> · <a href="${ROOT}pages/contact">Contact</a></nav>`;
const card = (p) => `<li><a href="${ROOT}products/${p._slug}">${imgOf(p) ? `<img src="${esc(imgOf(p))}" alt="${esc(p.title)}" width="240" height="300" loading="lazy">` : ""}<span>${esc(p.title)}</span></a>${p.sellOverride != null ? ` <b>${money(p.sellOverride)}</b>` : ""}</li>`;
const crumbsLD = (items) => ({ "@type": "BreadcrumbList", itemListElement: items.map(([n, u], i) => ({ "@type": "ListItem", position: i + 1, name: n, item: u })) });
const org = { "@type": "Organization", "@id": abs("#org"), name: brand, url: SITE, logo: abs("kulsums-logo.png") };

// ---------- write ----------
const out = new Map();
const put = (file, html) => out.set(file, html);
for (const p of products) {
  const c = catById[p.category] || { id: "others", name: "Products" }, url = abs(`products/${p._slug}`), img = imgOf(p), price = p.sellOverride;
  const desc = cut(`${p.title}${price != null ? " at " + money(price) : ""}. ${String(p.storeDesc || "").replace(/\n+/g, ". ")}`, 160);
  const ld = [{ "@context": "https://schema.org", "@type": "Product", name: p.title, sku: p.code || p.id, url, image: (p.media?.imgs || [img]).filter((u) => /^https?:/.test(u || "")).slice(0, 5),
    description: cut(p.storeDesc || p.title, 500), brand: { "@type": "Brand", name: brand }, category: c.name,
    ...(price != null ? { offers: { "@type": "Offer", url, priceCurrency: "INR", price: String(price), availability: p.stock === "out" ? "https://schema.org/OutOfStock" : "https://schema.org/InStock", itemCondition: "https://schema.org/NewCondition", seller: { "@id": abs("#org") } } } : {}) },
    { "@context": "https://schema.org", ...crumbsLD([["Home", SITE], [c.name, abs(`collections/${catSlug(c)}`)], [p.title, url]]) }];
  put(`products/${p._slug}.html`, page({ title: `${p.title} | ${brand}`, desc, url, image: img, type: "product", ld,
    body: `${nav()}<p><a href="${ROOT}">Home</a> / <a href="${ROOT}collections/${catSlug(c)}">${esc(c.name)}</a> / ${esc(p.title)}</p><article><h1>${esc(p.title)}</h1>${img ? `<img src="${esc(img)}" alt="${esc(p.title)}" width="480" height="600">` : ""}${price != null ? `<p><b>${money(price)}</b>${p.stock === "out" ? " · Sold out" : " · In stock"}</p>` : ""}${String(p.storeDesc || "").split("\n").filter(Boolean).map((l) => `<p>${esc(l)}</p>`).join("")}<p><a href="${ROOT}collections/${catSlug(c)}">More ${esc(c.name.toLowerCase())}</a></p></article>` }));
}
function collection(slug, name, list, intro) {
  const url = abs(`collections/${slug}`);
  put(`collections/${slug}.html`, page({ title: `${name} | ${brand}`, desc: cut(`Shop ${name.toLowerCase()} at ${brand}. ${intro || st.seo?.description || st.tagline || ""} ${list.length} designs available.`, 160), url, image: imgOf(list[0] || {}),
    ld: [{ "@context": "https://schema.org", "@type": "CollectionPage", name, url, mainEntity: { "@type": "ItemList", itemListElement: list.slice(0, 50).map((p, i) => ({ "@type": "ListItem", position: i + 1, url: abs(`products/${p._slug}`), name: p.title })) } },
      { "@context": "https://schema.org", ...crumbsLD([["Home", SITE], [name, url]]) }],
    body: `${nav()}<h1>${esc(name)}</h1><p>${list.length} designs</p><ul>${list.map(card).join("")}</ul>` }));
}
collection("new-arrivals", "New arrivals", newList, "Our newest pieces.");
for (const c of mainCats) collection(catSlug(c), c.name, products.filter((p) => groupIds(c).includes(p.category)));
for (const c of cats.filter((x) => x.parent && catOn(x) && products.some((p) => p.category === x.id))) collection(catSlug(c), c.name, products.filter((p) => p.category === c.id));
const pol = st.policies || {}, sup = st.support || {};
const info = [["about-us", "About us", pol.about], ["shipping", "Shipping", pol.shipping], ["returns", "Returns and exchanges", pol.returns],
  ["contact", "Contact us", [sup.whatsapp && `WhatsApp: ${sup.whatsapp}`, sup.phone && `Phone: ${sup.phone}`, sup.email && `Email: ${sup.email}`, sup.hours].filter(Boolean).join("\n")]];
for (const [slug, name, text] of info) put(`pages/${slug}.html`, page({ title: `${name} | ${brand}`, desc: cut(text || `${name} at ${brand}.`, 160), url: abs(`pages/${slug}`),
  ld: [{ "@context": "https://schema.org", ...crumbsLD([["Home", SITE], [name, abs(`pages/${slug}`)]]) }], body: `${nav()}<h1>${esc(name)}</h1>${String(text || "").split("\n").filter(Boolean).map((l) => `<p>${esc(l)}</p>`).join("")}` }));
for (const [file, name, d] of [["offers", "Offers", `Current offers and coupon codes at ${brand}.`], ["stories", "Customer reviews and stories", `Real reviews from ${brand} customers.`], ["videos", "Videos", `Collection videos from ${brand}.`], ["news", "Announcements", `News and new collections from ${brand}.`], ["combos", "Combo deals", `Save more with combo deals at ${brand}.`]])
  put(`${file}.html`, page({ title: `${name} | ${brand}`, desc: d, url: abs(file), body: `${nav()}<h1>${esc(name)}</h1><p>${esc(d)}</p>` }));
for (const [file, name] of [["cart", "Your bag"], ["checkout", "Checkout"], ["wishlist", "Wishlist"], ["track", "Track your order"], ["search", "Search"]])
  put(`${file}.html`, page({ title: `${name} | ${brand}`, desc: st.seo?.description || st.tagline || brand, url: abs(file), noindex: true }));
put("404.html", page({ title: `Page not found | ${brand}`, desc: st.seo?.description || brand, url: SITE, noindex: true }));

// remove pages this script made earlier for products or collections that are no longer live
for (const dir of ["products", "collections", "pages"]) {
  if (!existsSync(join(root, dir))) mkdirSync(join(root, dir), { recursive: true });
  for (const f of readdirSync(join(root, dir))) { const rel = `${dir}/${f}`; if (f.endsWith(".html") && !out.has(rel) && read(rel).includes(MARK)) { unlinkSync(join(root, rel)); console.log("removed", rel); } }
}
for (const [file, html] of out) writeFileSync(join(root, file), html);

// ---------- sitemap.xml and robots.txt ----------
const day = (t) => new Date(t || Date.now()).toISOString().slice(0, 10);
const urls = [[SITE, day(), "1.0"], [abs("collections/new-arrivals"), day(), "0.9"], ...mainCats.map((c) => [abs(`collections/${catSlug(c)}`), day(), "0.8"]),
  ...products.map((p) => [abs(`products/${p._slug}`), day(p.updatedAt || p.createdAt), "0.7", imgOf(p), p.title]),
  ...info.map(([s]) => [abs(`pages/${s}`), day(), "0.4"]), [abs("offers"), day(), "0.5"]];
writeFileSync(join(root, "sitemap.xml"), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n${urls.map(([u, d, pr, img, t]) =>
  `  <url><loc>${esc(u)}</loc><lastmod>${d}</lastmod><priority>${pr}</priority>${img ? `<image:image><image:loc>${esc(img)}</image:loc><image:title>${esc(t)}</image:title></image:image>` : ""}</url>`).join("\n")}\n</urlset>\n`);
const aiSearch = ["OAI-SearchBot", "ChatGPT-User", "Claude-SearchBot", "Claude-User", "PerplexityBot", "Perplexity-User", "DuckAssistBot"];
const aiTrain = ["GPTBot", "ClaudeBot", "Google-Extended", "Applebot-Extended", "CCBot", "meta-externalagent", "Bytespider", "Amazonbot"];
const rule = (bots, allow) => bots.map((b) => `User-agent: ${b}\n${allow ? "Allow" : "Disallow"}: /`).join("\n\n");
writeFileSync(join(root, "robots.txt"), `# ${brand}\nUser-agent: *\nAllow: /\nDisallow: ${ROOT}cart\nDisallow: ${ROOT}checkout\nDisallow: ${ROOT}wishlist\nDisallow: ${ROOT}search\nDisallow: ${ROOT}track\nDisallow: ${ROOT}order/\n\n# AI search assistants\n${rule(aiSearch, st.seo?.aiSearch !== false)}\n\n# AI model training\n${rule(aiTrain, !!st.seo?.aiTraining)}\n\nSitemap: ${abs("sitemap.xml")}\n`);
console.log(`Built ${products.length} product pages, ${mainCats.length + 1} collections, sitemap with ${urls.length} addresses, for ${SITE}`);
