// Kulsums Collection: builds search-engine pages from the live catalogue.
// Run by GitHub Actions (.github/workflows/seo.yml), or by hand: node scripts/build-seo.mjs
//
// For every live product it writes products/<name>.html, so https://yoursite/products/<name> is a real page
// with its own title, description, photo, price and Google product data, readable without JavaScript.
// Also: collections/<name>.html, pages/*.html, offers.html and the other shop pages, 404.html, sitemap.xml, robots.txt,
// and the Google Merchant Center feed: merchant-feed.tsv (for Google Sheets) and merchant-feed.xml (for a direct fetch).
// Each page is index.html with the right details filled in, so the full store still opens on top of it.
// Uses only the public data the store already shows to shoppers (the same public key as config.js).
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, unlinkSync } from "node:fs";
import { join } from "node:path";

const MARK = "<!-- generated by scripts/build-seo.mjs -->";
const root = process.cwd();
const read = (f) => readFileSync(join(root, f), "utf8");

// ---------- settings ----------
const cfg = read("config.js");
const SB_URL = (cfg.match(/supabaseUrl\s*:\s*['"]([^'"]+)['"]/) || [])[1];
const SB_KEY = (cfg.match(/supabaseKey\s*:\s*['"]([^'"]+)['"]/) || [])[1];
if (!SB_URL || !SB_KEY) { console.error("config.js does not have supabaseUrl and supabaseKey."); process.exit(1); }

async function kv(keys) {
  const url = `${SB_URL.replace(/\/$/, "")}/rest/v1/kv?select=key,value&key=in.(${keys.map((k) => `"${k}"`).join(",")})`;
  const r = await fetch(url, { headers: { apikey: SB_KEY, Authorization: `Bearer ${SB_KEY}` } });
  if (!r.ok) throw new Error(`Supabase said ${r.status}: ${await r.text()}`);
  return Object.fromEntries((await r.json()).map((x) => [x.key, x.value]));
}
const data = await kv(["kc:settings", "kc:categories", "kc:catalog"]);
const st = data["kc:settings"] || {};
const cats = data["kc:categories"] || [];
const catalog = data["kc:catalog"] || [];
const brand = st.brand || "Kulsums Collection";
const cname = existsSync(join(root, "CNAME")) ? read("CNAME").trim() : "";
let SITE = String(process.env.SITE_URL || st.seo?.siteUrl || (cname ? `https://${cname}` : "")).trim().replace(/[#?].*$/, "").replace(/\/?$/, "/");
if (!/^https?:\/\//.test(SITE)) { console.error("Set your website address: add a CNAME file, or Settings > Search and sharing > Website address, or SITE_URL."); process.exit(1); }
const ROOT = new URL(SITE).pathname; // "/" for kulsumscollection.com
const abs = (p) => SITE + p.replace(/^\//, "");

// ---------- the same address rules as the store ----------
const slugify = (t) => String(t || "").toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/&/g, " and ").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 70) || "item";
const prodSlug = (p) => p.slug || `${slugify(p.title)}-${String(p.code || p.id).toLowerCase()}`;
const catSlug = (c) => c.slug || (/^[a-z0-9-]{2,40}$/.test(c.id) ? c.id : slugify(c.name));
const esc = (s) => String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
const cut = (s, n) => { s = String(s || "").replace(/\s+/g, " ").trim(); return s.length > n ? s.slice(0, n - 1).replace(/\s\S*$/, "") + "…" : s; };
const money = (n) => (n == null || n === "" ? "" : "₹" + Number(n).toLocaleString("en-IN"));
// Page titles and descriptions (the same rules as the store): what it is, price, key details, why buy here.
const titleCase = (t) => String(t).replace(/\b\w/g, (m) => m.toUpperCase());
const CAT_SEO = { kids: "Kids Wear", men: "Men's Wear", home: "Home Decor", western: "Western Wear", jewellery: "Jewellery", footwear: "Footwear" };
const catPlural = (c) => CAT_SEO[c?.id] || CAT_SEO[c?.parent] || titleCase(String(c?.name || "").replace(/\s*&.*$/, "").trim() || "Collection");
const spec = (p, k) => ((p.storeDesc || "").match(new RegExp(`^${k}\\s*:\\s*(.+)$`, "im")) || [])[1]?.trim() || "";
const trustLine = () => [st.payments?.cod?.enabled !== false && "Cash on delivery", Number(st.shipping?.freeAbove) > 0 && `free shipping above ${money(st.shipping.freeAbove)}`].filter(Boolean).join(", ");
function productTitle(p, c) { const a = `${p.title} | Buy ${catPlural(c)} Online | ${brand}`; return c && c.id !== "others" && a.length <= 68 ? a : `${p.title} | ${brand}`; }
function productDesc(p) { const fab = spec(p, "fabric"), work = spec(p, "work"), size = spec(p, "size"), price = p.sellOverride;
  const facts = [fab && `${fab} fabric`, work && `${work.toLowerCase()}${/work$/i.test(work) ? "" : " work"}`, size && (/^age/i.test(size) ? `for ${size.toLowerCase()}` : `sizes ${size}`)].filter(Boolean).join(", ");
  return cut(`Buy ${p.title} online at ${brand}${price != null ? ` for ${money(price)}` : ""}.${facts ? " " + facts.charAt(0).toUpperCase() + facts.slice(1) + "." : ""}${trustLine() ? " " + trustLine() + "." : ""}`, 158); }
const imgOf = (p) => { const u = p.media?.imgs?.[0] || p.media?.th || ""; return /^https?:\/\//.test(u) ? u : ""; };

const catById = Object.fromEntries(cats.map((c) => [c.id, c]));
const catOn = (c) => { for (let x = c, i = 0; x && i < 5; x = catById[x.parent], i++) if (x.enabled === false) return false; return !!c; };
const products = catalog.filter((p) => p.published !== false && catOn(catById[p.category] || { enabled: true })).sort((a, b) => (b.createdAt || 0) - (a.createdAt || 0));
const used = new Set();
for (const p of products) { let s = prodSlug(p), b = s, i = 2; while (used.has(s)) s = `${b}-${i++}`; used.add(s); p._slug = s; }
const groupIds = (c) => [c.id, ...cats.filter((x) => x.parent === c.id).map((x) => x.id)];
const mainCats = cats.filter((c) => c.id !== "others" && catOn(c) && !c.parent && products.some((p) => groupIds(c).includes(p.category)));   // only collections that have products
const newDays = st.catalog?.newDays || 14;
const fresh = products.filter((p) => Date.now() - (p.createdAt || 0) < newDays * 864e5);
const newList = [...fresh, ...products.filter((p) => !fresh.includes(p))].slice(0, 10);

// ---------- page template ----------
const template = read("index.html");
function fixPaths(html) {
  // Pages live in sub-folders, so file names outside the scripts become absolute (/config.js, /kulsums-logo.png).
  return html.split(/(<script\b[^>]*>[\s\S]*?<\/script>)/i).map((part, i) => (i % 2 ? part.replace(/(<script\b[^>]*\bsrc=")(?!https?:|\/|data:)([^"]+)"/i, `$1${ROOT}$2"`)
    : part.replace(/\b(src|href|content)="(?!https?:|data:|#|\/|mailto:|tel:|\$|width=|index,|summary|website|en_IN|#)([\w./-]+\.(?:js|png|jpe?g|webp|svg|ico|txt|json|xml|html))"/g, `$1="${ROOT}$2"`))).join("");
}
// Public settings without large embedded pictures, for the data each page carries.
const slimSettings = JSON.parse(JSON.stringify(st, (k, v) => (typeof v === "string" && v.startsWith("data:") && v.length > 2000 ? undefined : v)));
const slimProduct = ({ fp, vendorPrice, description, ...p }) => p;   // only what shoppers can see
function page({ title, desc, url, image, type = "website", noindex = false, ld = [], body = "", preload = null }) {
  let h = fixPaths(template);
  const set = (re, val) => { h = re.test(h) ? h.replace(re, val) : h.replace("</head>", val + "\n</head>"); };
  set(/<title>[\s\S]*?<\/title>/, `<title>${esc(title)}</title>`);
  set(/<meta name="description"[^>]*>/, `<meta name="description" content="${esc(desc)}">`);
  set(/<meta name="robots"[^>]*>/, `<meta name="robots" content="${noindex ? "noindex,follow" : "index,follow,max-image-preview:large"}">`);
  set(/<meta property="og:title"[^>]*>/, `<meta property="og:title" content="${esc(title)}">`);
  set(/<meta property="og:description"[^>]*>/, `<meta property="og:description" content="${esc(desc)}">`);
  set(/<meta property="og:type"[^>]*>/, `<meta property="og:type" content="${type}">`);
  if (image) set(/<meta property="og:image"[^>]*>/, `<meta property="og:image" content="${esc(image)}">`);
  const extra = [`<link rel="canonical" href="${esc(url)}">`, `<meta property="og:url" content="${esc(url)}">`, `<meta name="twitter:title" content="${esc(title)}">`, `<meta name="twitter:description" content="${esc(desc)}">`,
    image ? `<meta name="twitter:image" content="${esc(image)}">` : "",
    preload ? `<script type="application/json" id="kc-preload">${JSON.stringify({ settings: slimSettings, categories: cats, products: (preload.products || []).map(slimProduct) }).replace(/</g, "\\u003c")}</script>` : "", ld.length ? `<script type="application/ld+json">${JSON.stringify(ld.length === 1 ? ld[0] : { "@context": "https://schema.org", "@graph": ld }).replace(/</g, "\\u003c")}</script>` : ""].filter(Boolean).join("\n");
  h = h.replace("</head>", `${MARK}\n${extra}\n</head>`);
  if (body) h = h.replace(/<div id="app">[\s\S]*?<\/div><\/div>/, `<div id="app"><main class="shop-main ssr" id="main" style="max-width:1100px;margin:0 auto;padding:24px 20px;font-family:system-ui,sans-serif">${body}</main></div>`);
  return h;
}
const nav = () => `<nav aria-label="Shop"><a href="${ROOT}">Home</a> · <a href="${ROOT}collections/new-arrivals">New arrivals</a>${mainCats.map((c) => ` · <a href="${ROOT}collections/${catSlug(c)}">${esc(c.name)}</a>`).join("")} · <a href="${ROOT}pages/about-us">About us</a> · <a href="${ROOT}pages/contact">Contact</a></nav>`;
const card = (p) => `<li><a href="${ROOT}products/${p._slug}">${imgOf(p) ? `<img src="${esc(imgOf(p))}" alt="${esc(p.title)}" width="240" height="300" loading="lazy">` : ""}<span>${esc(p.title)}</span></a>${p.sellOverride != null ? ` <b>${money(p.sellOverride)}</b>` : ""}</li>`;
const crumbsLD = (items) => ({ "@type": "BreadcrumbList", itemListElement: items.map(([n, u], i) => ({ "@type": "ListItem", position: i + 1, name: n, item: u })) });
const org = { "@type": "Organization", "@id": abs("#org"), name: brand, url: SITE, logo: abs("kulsums-logo.png") };

// ---------- write ----------
const out = new Map();
const put = (file, html) => out.set(file, html);
for (const p of products) {
  const c = catById[p.category] || { id: "others", name: "Products" }, url = abs(`products/${p._slug}`), img = imgOf(p), price = p.sellOverride;
  const desc = productDesc(p);
  const ld = [{ "@context": "https://schema.org", "@type": "Product", name: p.title, sku: p.code || p.id, url, image: (p.media?.imgs || [img]).filter((u) => /^https?:/.test(u || "")).slice(0, 5),
    description: cut(p.storeDesc || p.title, 500), brand: { "@type": "Brand", name: brand }, category: c.name,
    ...(price != null ? { offers: { "@type": "Offer", url, priceCurrency: "INR", price: String(price), availability: p.stock === "out" ? "https://schema.org/OutOfStock" : "https://schema.org/InStock", itemCondition: "https://schema.org/NewCondition", seller: { "@id": abs("#org") } } } : {}) },
    { "@context": "https://schema.org", ...crumbsLD([["Home", SITE], [c.name, abs(`collections/${catSlug(c)}`)], [p.title, url]]) }];
  put(`products/${p._slug}.html`, page({ title: productTitle(p, c), desc, url, image: img, type: "product", ld, preload: { products: [p, ...products.filter((x) => x !== p && x.category === p.category).slice(0, 8)] },
    body: `${nav()}<p><a href="${ROOT}">Home</a> / <a href="${ROOT}collections/${catSlug(c)}">${esc(c.name)}</a> / ${esc(p.title)}</p><article><h1>${esc(p.title)}</h1>${img ? `<img src="${esc(img)}" alt="${esc(p.title)}" width="480" height="600">` : ""}${price != null ? `<p><b>${money(price)}</b>${p.stock === "out" ? " · Sold out" : " · In stock"}</p>` : ""}${String(p.storeDesc || "").split("\n").filter(Boolean).map((l) => `<p>${esc(l)}</p>`).join("")}<p><a href="${ROOT}collections/${catSlug(c)}">More ${esc(c.name.toLowerCase())}</a></p></article>` }));
}
function collection(slug, name, list, intro) {
  const url = abs(`collections/${slug}`);
  const fabs = [...new Set(list.map((p) => spec(p, "fabric")).filter(Boolean))].slice(0, 3);
  put(`collections/${slug}.html`, page({ title: slug === "new-arrivals" ? `New Arrivals | Latest Designs | ${brand}` : `${titleCase(name)} | Buy ${catPlural({ name })} Online | ${brand}`, preload: { products: list.slice(0, 60) },
    desc: cut(`Shop ${list.length} ${name.toLowerCase()} online at ${brand}${fabs.length ? `, in ${fabs.join(", ")}` : ""}. Handpicked designs, delivered across India${trustLine() ? ` with ${trustLine().toLowerCase()}` : ""}.`, 158), url, image: imgOf(list[0] || {}),
    ld: [{ "@context": "https://schema.org", "@type": "CollectionPage", name, url, mainEntity: { "@type": "ItemList", itemListElement: list.slice(0, 50).map((p, i) => ({ "@type": "ListItem", position: i + 1, url: abs(`products/${p._slug}`), name: p.title })) } },
      { "@context": "https://schema.org", ...crumbsLD([["Home", SITE], [name, url]]) }],
    body: `${nav()}<h1>${esc(name)}</h1><p>${list.length} designs</p><ul>${list.map(card).join("")}</ul>` }));
}
collection("new-arrivals", "New arrivals", newList, "Our newest pieces.");
for (const c of mainCats) collection(catSlug(c), c.name, products.filter((p) => groupIds(c).includes(p.category)));
for (const c of cats.filter((x) => x.parent && catOn(x) && products.some((p) => p.category === x.id))) collection(catSlug(c), c.name, products.filter((p) => p.category === c.id));
const pol = st.policies || {}, sup = st.support || {};
const info = [["about-us", "About us", pol.about], ["shipping", "Shipping", pol.shipping], ["returns", "Returns and exchanges", pol.returns],
  ["contact", "Contact us", [sup.whatsapp && `WhatsApp: ${sup.whatsapp}`, sup.phone && `Phone: ${sup.phone}`, sup.email && `Email: ${sup.email}`, sup.hours].filter(Boolean).join("\n")]];
for (const [slug, name, text] of info) put(`pages/${slug}.html`, page({ title: `${name} | ${brand}`, preload: { products: [] }, desc: cut(text || `${name} at ${brand}.`, 160), url: abs(`pages/${slug}`),
  ld: [{ "@context": "https://schema.org", ...crumbsLD([["Home", SITE], [name, abs(`pages/${slug}`)]]) }], body: `${nav()}<h1>${esc(name)}</h1>${String(text || "").split("\n").filter(Boolean).map((l) => `<p>${esc(l)}</p>`).join("")}` }));
for (const [file, name, d] of [["offers", "Offers", `Current offers and coupon codes at ${brand}.`], ["stories", "Customer reviews and stories", `Real reviews from ${brand} customers.`], ["videos", "Videos", `Collection videos from ${brand}.`], ["news", "Announcements", `News and new collections from ${brand}.`], ["combos", "Combo deals", `Save more with combo deals at ${brand}.`]])
  put(`${file}.html`, page({ title: `${name} | ${brand}`, desc: d, url: abs(file), body: `${nav()}<h1>${esc(name)}</h1><p>${esc(d)}</p>` }));
for (const [file, name] of [["cart", "Your bag"], ["checkout", "Checkout"], ["wishlist", "Wishlist"], ["track", "Track your order"], ["search", "Search"], ["emi", "Your EMI plan"], ["hi", "Welcome"]])
  put(`${file}.html`, page({ title: `${name} | ${brand}`, desc: st.seo?.description || st.tagline || brand, url: abs(file), noindex: true }));
put("404.html", page({ title: `Page not found | ${brand}`, desc: st.seo?.description || brand, url: SITE, noindex: true }));

// remove pages this script made earlier for products or collections that are no longer live
for (const dir of ["products", "collections", "pages"]) {
  if (!existsSync(join(root, dir))) mkdirSync(join(root, dir), { recursive: true });
  for (const f of readdirSync(join(root, dir))) { const rel = `${dir}/${f}`; if (f.endsWith(".html") && !out.has(rel) && read(rel).includes(MARK)) { unlinkSync(join(root, rel)); console.log("removed", rel); } }
}
for (const [file, html] of out) writeFileSync(join(root, file), html);

// ---------- sitemap.xml and robots.txt ----------
const day = (t) => new Date(t || Date.now()).toISOString().slice(0, 10);
const urls = [[SITE, day(), "1.0"], [abs("collections/new-arrivals"), day(), "0.9"], ...mainCats.map((c) => [abs(`collections/${catSlug(c)}`), day(), "0.8"]),
  ...products.map((p) => [abs(`products/${p._slug}`), day(p.updatedAt || p.createdAt), "0.7", imgOf(p), p.title]),
  ...info.map(([s]) => [abs(`pages/${s}`), day(), "0.4"]), [abs("offers"), day(), "0.5"]];
writeFileSync(join(root, "sitemap.xml"), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n${urls.map(([u, d, pr, img, t]) =>
  `  <url><loc>${esc(u)}</loc><lastmod>${d}</lastmod><priority>${pr}</priority>${img ? `<image:image><image:loc>${esc(img)}</image:loc><image:title>${esc(t)}</image:title></image:image>` : ""}</url>`).join("\n")}\n</urlset>\n`);
const aiSearch = ["OAI-SearchBot", "ChatGPT-User", "Claude-SearchBot", "Claude-User", "PerplexityBot", "Perplexity-User", "DuckAssistBot"];
const aiTrain = ["GPTBot", "ClaudeBot", "Google-Extended", "Applebot-Extended", "CCBot", "meta-externalagent", "Bytespider", "Amazonbot"];
const rule = (bots, allow) => bots.map((b) => `User-agent: ${b}\n${allow ? "Allow" : "Disallow"}: /`).join("\n\n");
writeFileSync(join(root, "robots.txt"), `# ${brand}\nUser-agent: *\nAllow: /\nDisallow: ${ROOT}cart\nDisallow: ${ROOT}checkout\nDisallow: ${ROOT}wishlist\nDisallow: ${ROOT}search\nDisallow: ${ROOT}track\nDisallow: ${ROOT}order/\nDisallow: ${ROOT}emi\nDisallow: ${ROOT}hi\n\n# AI search assistants\n${rule(aiSearch, st.seo?.aiSearch !== false)}\n\n# AI model training\n${rule(aiTrain, !!st.seo?.aiTraining)}\n\nSitemap: ${abs("sitemap.xml")}\n`);

// ---------- Google Merchant Center feed (merchant-feed.tsv for Google Sheets, merchant-feed.xml for a direct fetch) ----------
const GOOGLE_CAT = {
  sarees: "Apparel & Accessories > Clothing > Traditional & Ceremonial Clothing > Saris & Lehengas",
  lehengas: "Apparel & Accessories > Clothing > Traditional & Ceremonial Clothing > Saris & Lehengas",
  suits: "Apparel & Accessories > Clothing > Traditional & Ceremonial Clothing",
  kurtis: "Apparel & Accessories > Clothing > Shirts & Tops",
  dupattas: "Apparel & Accessories > Clothing Accessories > Scarves & Shawls",
  western: "Apparel & Accessories > Clothing", kids: "Apparel & Accessories > Clothing", men: "Apparel & Accessories > Clothing",
  bags: "Apparel & Accessories > Handbags, Wallets & Cases > Handbags", jewellery: "Apparel & Accessories > Jewelry",
  footwear: "Apparel & Accessories > Shoes", home: "Home & Garden > Decor",
};
const guessCat = (c, p) => { const t = `${c?.name || ""} ${p.title}`.toLowerCase();
  return GOOGLE_CAT[c?.id] || GOOGLE_CAT[c?.parent] || (/saree|sari|lehenga/.test(t) ? GOOGLE_CAT.sarees : /kurti|kurta|top|tunic/.test(t) ? GOOGLE_CAT.kurtis : /suit|salwar|anarkali|sharara/.test(t) ? GOOGLE_CAT.suits
    : /dupatta|stole|shawl/.test(t) ? GOOGLE_CAT.dupattas : /jewel|necklace|earring|jhumka|bangle/.test(t) ? GOOGLE_CAT.jewellery : /bag|clutch|potli/.test(t) ? GOOGLE_CAT.bags : /footwear|jutti|sandal|chappal/.test(t) ? GOOGLE_CAT.footwear : ""); };
const COLOURS = ["black","white","off white","cream","ivory","beige","gold","golden","silver","grey","red","maroon","wine","pink","rani pink","baby pink","peach","coral","orange","rust","mustard","yellow","lemon","green","bottle green","olive","mint","sea green","teal","turquoise","blue","navy","sky blue","royal blue","purple","lavender","lilac","mauve","magenta","brown","multicolour","multicolor"];
const tc = (w) => w.replace(/\b\w/g, (m) => m.toUpperCase());
function feedRow(p) {
  const c = catById[p.category], price = Number(p.sellOverride), imgs = (p.media?.imgs || [imgOf(p)]).filter((u) => /^https?:\/\//.test(u || ""));
  if (!(price > 0) || !imgs.length) return null; // Merchant Center needs a price and a photo
  const text = `${p.title}\n${p.storeDesc || ""}`, low = text.toLowerCase();
  const material = ((p.storeDesc || "").match(/^(?:fabric|material)\s*:\s*(.+)$/im) || [])[1]?.split(/[,/]| and /)[0].trim() || "";
  const named = (p.colors || []).map((x) => x?.name).filter((n) => n && !/^colou?r \d+$/i.test(n));
  const found = COLOURS.filter((w) => new RegExp(`\\b${w}\\b`).test(low)).filter((w, i, a) => !a.some((o) => o !== w && o.includes(w))).sort((a, b) => low.search(new RegExp(`\\b${a}\\b`)) - low.search(new RegExp(`\\b${b}\\b`)));   // in the order the description mentions them
  const colour = [...new Set([...named, ...found.map(tc)])].slice(0, 3).join("/");
  const mrp = Number(p.mrp), onSale = mrp > price;
  const isNew = fresh.includes(p), kids = c?.id === "kids" || c?.parent === "kids", men = c?.id === "men" || c?.parent === "men", home = c?.id === "home";
  const band = price < 500 ? "under_500" : price < 1000 ? "500_999" : price < 2000 ? "1000_1999" : "2000_plus";
  const body = String(p.storeDesc || "").split(/\n+/).map((l) => l.trim().replace(/[.!]?$/, ".")).filter((l) => l.length > 1).join(" ");
  const desc = cut([body, `From ${brand}.`].filter(Boolean).join(" "), 4900);
  return {
    id: p.code || p.id, title: cut(p.title, 150), description: desc || p.title, link: abs(`products/${p._slug}`), image_link: imgs[0],
    additional_image_link: imgs.slice(1, 11).join(","), availability: p.stock === "out" ? "out_of_stock" : "in_stock",
    price: `${(onSale ? mrp : price).toFixed(2)} INR`, sale_price: onSale ? `${price.toFixed(2)} INR` : "", brand, condition: "new",
    google_product_category: guessCat(c, p), product_type: c ? (c.parent && catById[c.parent] ? `${catById[c.parent].name} > ${c.name}` : c.name) : "",
    gender: home ? "" : men ? "male" : kids ? "unisex" : "female", age_group: home ? "" : kids ? "kids" : "adult",
    color: colour, material: tc(material.toLowerCase()), identifier_exists: "no",
    custom_label_0: c?.name || "", custom_label_1: isNew ? "new_arrival" : "", custom_label_2: band,
  };
}
const rows = products.map(feedRow).filter(Boolean), skipped = products.length - rows.length;
const COLS = ["id","title","description","link","image_link","additional_image_link","availability","price","sale_price","brand","condition","google_product_category","product_type","gender","age_group","color","material","identifier_exists","custom_label_0","custom_label_1","custom_label_2"];
const cell = (v) => String(v ?? "").replace(/[\t\r\n]+/g, " ").replace(/^[=+\-@]+/, "").trim();
writeFileSync(join(root, "merchant-feed.tsv"), [COLS.join("\t"), ...rows.map((r) => COLS.map((k) => cell(r[k])).join("\t"))].join("\n") + "\n");
const x = (v) => esc(cell(v));
writeFileSync(join(root, "merchant-feed.xml"), `<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0" xmlns:g="http://base.google.com/ns/1.0"><channel>\n<title>${x(brand)}</title><link>${x(SITE)}</link><description>${x(st.seo?.description || st.tagline || brand)}</description>\n${rows.map((r) =>
  `<item>${COLS.map((k) => k === "additional_image_link" ? r[k].split(",").filter(Boolean).map((u) => `<g:additional_image_link>${x(u)}</g:additional_image_link>`).join("") : r[k] ? `<g:${k}>${x(r[k])}</g:${k}>` : "").join("")}</item>`).join("\n")}\n</channel></rss>\n`);
console.log(`Merchant feed: ${rows.length} products${skipped ? `, ${skipped} left out because they have no selling price or no online photo` : ""}`);
console.log(`Built ${products.length} product pages, ${mainCats.length + 1} collections, sitemap with ${urls.length} addresses, for ${SITE}`);



